pipeline {

  agent { docker { image 'python:3.7' } }
  stages {
    stage('build') {
      steps {
        sh 'pip install --upgrade pip'
        sh 'python -m pip install -r ./automated-unit-tests/Jenkinsfile/requirements.txt'
      }
    }
    stage('test') {
      steps {
        sh 'pwd;ls *'
        sh 'python automated_unit_tests/test_suite.py'

      }
    }
  }
}
